#!/bin/bash
if [ -z "$PYFILE" ]; then
	echo "$PYFILE environment variable not set."
	exit 1
fi
	python3 -m py_compile "$PYFILE"
if [ $? -eq 0 ]; then
	echo "Compiling $PYFILE ..."
else
	echo "failed."
	exit 1
fi
